### ISSUE TITLE
Use the plugin in "plain" ImageJ

### ISSUE THREAD

**Issue by MarkRivers** [paulscherrerinstitute/ch.psi.imagej.hdf5#7]
I am running on Windows.

This plugin is working fine when I use Fiji.  

I would like it to also work on plain ImageJ.   When I try that, and select a file I get this error message:

```
java.lang.UnsatisfiedLinkError: hdf.hdf5lib.H5.H5dont_atexit()I
	at hdf.hdf5lib.H5.H5dont_atexit(Native Method)
	at hdf.hdf5lib.H5.loadH5Lib(H5.java:246)
	at hdf.hdf5lib.H5.<clinit>(H5.java:230)
	at hdf.hdf5lib.HDF5Constants.<clinit>(HDF5Constants.java:29)
	at hdf.object.h5.H5File.<init>(H5File.java:94)
	at hdf.object.h5.H5File.<init>(H5File.java:127)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at hdf.object.FileFormat.<clinit>(FileFormat.java:228)
	at ch.psi.imagej.hdf5.HDF5Reader.open(HDF5Reader.java:82)
	at ch.psi.imagej.hdf5.HDF5Reader.open(HDF5Reader.java:51)
	at ch.psi.imagej.hdf5.HDF5Reader.run(HDF5Reader.java:36)
	at ij.IJ.runUserPlugIn(IJ.java:241)
	at ij.IJ.runPlugIn(IJ.java:204)
	at ij.Executer.runCommand(Executer.java:150)
	at ij.Executer.run(Executer.java:68)
	at java.lang.Thread.run(Thread.java:745)
```

Any idea what the problem is?

**Comment by MarkRivers** [comment]
I should add that for both Fiji and ImageJ I just copied the .jar file from the Github Releases into the ImageJ/plugins folder.

**Comment by MarkRivers** [comment]
Both Fiji and ImageJ are the latest version 1.53f and are Java 1.8.0.

**Comment by MarkRivers** [comment]
I figured out the problem.  I had an older version (0.12) of the HDF5 plugin in my ImageJ directory, and that I could never make work.

I deleted ImageJ completely and reinstalled.  I then installed version 0.13.0 HDF5 plugin and it is working fine.

Sorry for the noise.
